name: CI-CD

# Controls when the workflow will run
# Triggers the workflow on push  events
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # installs required dependencies
      - name: Install dependencies
        run: npx yarn

     # Runs build command
      - name: Build
        run: npx yarn build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with: 
          name: assets
          path: dist
